stages:
  - build
  - IAC
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: boiledsteak/fyp-auction-app

# Build Stage: Build the frontend using Node.js
build-app:
  stage: build
  image: node:23.11.0-alpine3.21
  script:
    - npm install --prefix frontend
    - npm run build --prefix frontend
    - ls -la frontend/dist
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

terraform:
  stage: IAC
  image:
    name: hashicorp/terraform:latest
    entrypoint: ["/bin/sh", "-c"]
  variables:
     TF_TOKEN_app_terraform_io: ${HCP_TF_TKN}
  script:
    - terraform init
    - terraform plan
    - terraform apply -auto-approve


deploy:
  stage: deploy
  image: docker:24
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'